### ISSUE TITLE
decorate test/system/workarea/storefront/products_quickview_system_test.rb

### ISSUE THREAD

**Issue by roseliux** [workarea-commerce/workarea-product-quickview#4]
When I decorate the test/system/workarea/storefront/products_quickview_system_test.rb
the file generated have this class declare `decorate Storefront::ProductsQuickviewSystemTest`
digging into the code what you declare for this test was `Storefront::ProductQuickviewSystemTest`
Product without the S.
Is any way we can fix this so others dev don't found this similar issue.

**Comment by bencrouse** [comment]
Thanks for reporting, we'll get this patched.

**Comment by bencrouse** [comment]
Fixed in version 2.0.3 of this gem.

**Comment by roseliux** [comment]
Thanks
